"""add stripe fields to user and retry config to destination

Revision ID: e0ea752a3344
Revises: 
Create Date: 2026-03-13 17:35:04.550376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ea752a3344'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add retry columns to destinations with defaults for SQLite compatibility
    op.add_column('destinations', sa.Column('retry_enabled', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('destinations', sa.Column('max_retries', sa.Integer(), nullable=True, server_default='3'))
    op.add_column('destinations', sa.Column('retry_backoff_base_ms', sa.Integer(), nullable=True, server_default='1000'))
    op.add_column('destinations', sa.Column('retry_backoff_max_ms', sa.Integer(), nullable=True, server_default='60000'))
    # Add Stripe columns to users
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('destinations', 'retry_backoff_max_ms')
    op.drop_column('destinations', 'retry_backoff_base_ms')
    op.drop_column('destinations', 'max_retries')
    op.drop_column('destinations', 'retry_enabled')
    # ### end Alembic commands ###
